import { font } from "@/utils/constant";
import { useEffect, useState } from "react";
import {
    Pressable,
    StyleSheet,
    Text,
    View,
    Alert,
    ScrollView,
} from "react-native";
import { Calendar, ChevronDown, FileText } from "lucide-react-native";
import DateTimePicker from "@/components/date-time-picker";
import * as Print from 'expo-print';
import { useSQLiteContext } from "expo-sqlite";
import { useTransactionStore } from "@/utils/store/transaction.store";
import { router } from "expo-router";
import { useWalletStore } from "@/utils/store/wallet.store";

export default function Settings() {
    const db = useSQLiteContext();
    const [date, setDate] = useState(new Date());
    const [showDatePicker, setShowDatePicker] = useState(false);
    const [isExporting, setIsExporting] = useState(false);
    const { getTransactions, transactions } = useTransactionStore();
    const { wallets } = useWalletStore();

    const handleExport = async () => {
        setIsExporting(true);
        try {
            // 1. Generate HTML
            const html = createHTML(date);

            // 2. Print to File (Generate PDF)
            const { uri } = await Print.printToFileAsync({ html });
            console.log('File has been saved to:', uri);
            await Print.printAsync({ html, width: 595, height: 842 })

        } catch (error) {
            console.error(error);
            Alert.alert("Error", "Failed to export PDF.");
        } finally {
            setIsExporting(false);
        }
    };

    const createHTML = (selectedDate: Date) => {
        const monthYear = selectedDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

        const rows = transactions.map(t => `
            <tr>
                <td>${new Date(t.date * 1000).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })}</td>
                <td>${t.note}</td>
                <td style="color: ${t.type === 'income' ? 'green' : 'red'}">${t.type}</td>
                <td style="text-align: right;">${wallets.find(w => w.id === t.wallet_id)?.name}</td>
                <td style="text-align: right;">${t.amount}</td>
            </tr>
        `).join('');

        return `
            <html>
            <head>
                <style>
                    body { font-family: 'Helvetica', sans-serif; padding: 20px; }
                    h1 { text-align: center; color: #333; }
                    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                    th { background-color: #f2f2f2; color: #333; }
                    .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #888; }
                </style>
            </head>
            <body>
                    <h1>Transaction Report</h1>
                    <h3 style="text-align: center;">${monthYear}</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Note</th>
                            <th>Type</th>
                            <th>Wallet</th>
                            <th style="text-align: right;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${rows}
                    </tbody>
                </table>

                <div class="footer">
                    Generated by KHOROCH APP
                    <p>Print Date: ${new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                </div>
            </body>
            </html>
        `;
    }

    useEffect(() => {
        getTransactions({ date, db, limit: 10000 });
    }, [date]);

    return (
        <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Data Export</Text>
                <View style={styles.card}>
                    <Text style={styles.cardDescription}>
                        Select a month to download your transaction report as a PDF.
                    </Text>

                    {/* Month Selector */}
                    <Pressable style={styles.selector} onPress={() => setShowDatePicker(true)}>
                        <View style={styles.selectorIcon}>
                            <Calendar size={20} color="#555" />
                        </View>
                        <View style={{ flex: 1 }}>
                            <Text style={styles.selectorLabel}>Select Month</Text>
                            <Text style={styles.selectorValue}>
                                {date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
                            </Text>
                        </View>
                        <ChevronDown size={20} color="#999" />
                    </Pressable>

                    {/* Export Button */}
                    <Pressable
                        style={({ pressed }) => [
                            styles.exportButton,
                            pressed && { opacity: 0.9 },
                            isExporting && { backgroundColor: '#ccc' }
                        ]}
                        onPress={handleExport}
                        disabled={isExporting}
                    >
                        <FileText size={20} color="#fff" style={{ marginRight: 8 }} />
                        <Text style={styles.exportButtonText}>
                            {isExporting ? "Generating PDF..." : "Export as PDF"}
                        </Text>
                    </Pressable>
                </View>
            </View>

            <DateTimePicker
                isVisible={showDatePicker}
                onClose={() => setShowDatePicker(false)}
                onConfirm={(selectedDate) => {
                    setDate(selectedDate);
                }}
                initialDate={date}
                mode="date" // Using date mode, simplified for month selection
            />


            <View style={[styles.section, { marginTop: 20 }]}>
                <Text style={styles.sectionTitle}>Wallet</Text>
                <View style={styles.card}>
                    <Text style={styles.cardDescription}>
                        Add your wallet details to get started.
                    </Text>

                    <Pressable style={styles.exportButton} onPress={() => router.navigate('/wallet/create')}>
                        <FileText size={20} color="#fff" style={{ marginRight: 8 }} />
                        <Text style={styles.exportButtonText}>
                            Add Wallet
                        </Text>
                    </Pressable>
                    <Pressable style={styles.exportButton} onPress={() => router.navigate('/wallet/')}>
                        <FileText size={20} color="#fff" style={{ marginRight: 8 }} />
                        <Text style={styles.exportButtonText}>
                            Show All Wallets
                        </Text>
                    </Pressable>
                </View>
            </View>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f9f9f9",
        padding: 16,
    },
    section: {
        marginTop: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "600",
        fontFamily: font.HindSiliguri,
        marginBottom: 12,
        color: "#333",
    },
    card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#eee",
        gap: 16,
    },
    cardDescription: {
        fontSize: 14,
        color: "#666",
        fontFamily: font.HindSiliguri,
        lineHeight: 20,
    },
    selector: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f5f5f5",
        borderRadius: 8,
        padding: 12,
        borderWidth: 1,
        borderColor: "#e0e0e0",
    },
    selectorIcon: {
        marginRight: 12,
    },
    selectorLabel: {
        fontSize: 12,
        color: "#888",
        fontFamily: font.HindSiliguri,
    },
    selectorValue: {
        fontSize: 16,
        color: "#333",
        fontWeight: "500",
        fontFamily: font.HindSiliguri,
    },
    exportButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#000",
        borderRadius: 10,
        paddingVertical: 14,
    },
    exportButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        fontFamily: font.HindSiliguri,
    },
    buttonOutline: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
        paddingVertical: 14,
    },
    amountContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 32,
        // 
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: "#eee",

    },
    amountInput: {
        fontSize: 48,
        fontFamily: font.HindSiliguri,
        color: "#333",
        fontWeight: "bold",
        minWidth: 100,
        textAlign: "center",
    },
});